/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JCURandRTC_Native */

#ifndef _Included_JCURandRTC_Native
#define _Included_JCURandRTC_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JCURandRTC_Native
 * Method:    dvrng_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JCURandRTC_Native_dvrng_1create
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
