name: Conda Windows Publishment

on:
  push:
    branches: [ master ]
    paths:
      - 'conda_windows/meta.yaml'        

jobs:
  build_thrustrtc_windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
        with:    
          repository: fynv/ThrustRTC        
          submodules: true
          
      - uses: ilammy/msvc-dev-cmd@v1  
      
      - name: Create Dir build_python
        run: mkdir build_python
        
      - name: Configure CMake
        working-directory: ./build_python
        run: cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ../python   
        
      - name: Make
        working-directory: ./build_python    
        run: nmake

      - name: Make Install
        working-directory: ./build_python
        run: nmake install        
        
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: thrustrtc_binary_windows
          path: ./install

  build_windows_latest:
    needs: [build_thrustrtc_windows]    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download thrustrtc_binary_windows
      uses: actions/download-artifact@v2
      with:
        name: thrustrtc_binary_windows
        path: ./install     

    - name: Set up Python 3.8
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8

    - uses: ilammy/msvc-dev-cmd@v1        

    - name: Set Always Yes
      run: conda config --set always_yes yes

    - name: Install conda tools
      run: conda install conda-build anaconda-client

    - name: Set Auto Upload
      run: conda config --set anaconda_upload yes

    - name: conda build and release
      run: conda-build conda_windows --no-test --user fyplus --token ${{ secrets.ANACONDA_TOKEN }}
